version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "daily" }
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels: [dependencies, github-actions]

  - package-ecosystem: "docker"
    directory: "/ann/src/main/python/dataflow/worker_harness/Dockerfile"
    schedule: { interval: "daily" }
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels: [dependencies, docker]
    ignore: &ignore_major_minor_updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
